server:
    port: 8086
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/hateoas-test
        username: webadmin
        password: webadmin
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create-drop
        show-sql: true
